### ISSUE TITLE
Play&Save - Error when trying to abort a save 

### ISSUE THREAD

**Issue by skronstein** [krontech/chronos-gui-2#50]
Traceback (most recent call last):
  File "/root/chronos-gui-2/chronosGui2/screens/play_and_save.py", line 843, in onSaveClicked
    raise e #TODO: Display proper errors.
  File "/root/chronos-gui-2/chronosGui2/screens/play_and_save.py", line 841, in onSaveClicked
    self.saveMarkedRegion()
  File "/root/chronos-gui-2/chronosGui2/screens/play_and_save.py", line 713, in saveMarkedRegion
    settings.value('savedFileMaxBitrate', 40) * 1000000.0,
  File "/root/chronos-gui-2/chronosGui2/api.py", line 107, in callSync
    raise DBusException("%s: %s" % (msg.error().name(), msg.error().message()))
chronosGui2.api.DBusException: org.freedesktop.DBus.GLib.UnmappedError.CamParametersQuark.Code0: Encoding in progress
0
[3] > /root/chronos-gui-2/chronosGui2/api.py(107)callSync()
-> raise DBusException("%s: %s" % (msg.error().name(), msg.error().message()))

**Comment by skronstein** [comment]
This message showed up when saving a large raw file to a fat32 drive, so it's probably related to the 4GB filesize limit of the fat32 filesystem.
